<?php

/**
 * @file
 * Contains d8learning.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function d8learning_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the d8learning module.
    case 'help.page.d8learning':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}


/**
 * Theme hook
 */


function d8learning_theme($existing, $type, $theme, $path) {
  return [
    'weather_block' => [
      'variables' => [
        'city_value' => 'city_value',
      ],
    ],
    'cblock' => [
      'variables' => [
        'cvalue' => 'cvalue',
      ],
    ],
  ];
}

